<?xml version="1.0" encoding="UTF-8"?><testrun name="ParserTest" project="Project1" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="ParserTest" time="0.0">
    <testcase name="test" classname="ParserTest" time="0.0">
      <error>student.testingsupport.ExitCalledException: System.exit(0)&#13;
	at student.testingsupport.ExitPreventingSecurityManager.checkExit(ExitPreventingSecurityManager.java:134)&#13;
	at java.base/java.lang.Runtime.exit(Runtime.java:113)&#13;
	at java.base/java.lang.System.exit(System.java:1860)&#13;
	at Parser.initializeComponents(Parser.java:43)&#13;
	at ParserTest.test(ParserTest.java:12)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)&#13;
	at student.testingsupport.junit4.RunTestMethodWrapper.evaluate(RunTestMethodWrapper.java:74)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#13;
	at java.base/java.lang.Thread.run(Thread.java:833)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
